import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { installHook, removeHook } from '../utils/hooks.js';
import { c, AGENTCROW_START, AGENTCROW_END, GLOBAL_DIR, GLOBAL_MD } from '../utils/constants.js';

export function cmdOff(global: boolean = false): void {
  const base = global ? path.join(os.homedir(), '.claude') : path.join(process.cwd(), '.claude');
  const claudeMd = path.join(base, 'CLAUDE.md');
  const backupMd = path.join(base, 'CLAUDE.md.agentcrow-backup');
  const agentsDir = path.join(base, 'agents');

  if (!fs.existsSync(claudeMd)) {
    console.log('\x1b[33m⚠ AgentCrow is already off (no .claude/CLAUDE.md found)\x1b[0m');
    return;
  }

  const content = fs.readFileSync(claudeMd, 'utf-8');
  if (!content.includes('AgentCrow') && !content.includes('agentcrow')) {
    console.log('\x1b[33m⚠ .claude/CLAUDE.md exists but was not generated by AgentCrow. Skipping.\x1b[0m');
    return;
  }

  const startIdx = content.indexOf(AGENTCROW_START);
  const endIdx = content.indexOf(AGENTCROW_END);

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    const before = content.slice(0, startIdx);
    const after = content.slice(endIdx + AGENTCROW_END.length);
    const remaining = (before + after).replace(/\n{3,}/g, '\n\n').trim();

    if (remaining.length > 0) {
      fs.writeFileSync(backupMd, content, 'utf-8');
      fs.writeFileSync(claudeMd, remaining + '\n', 'utf-8');
    } else {
      fs.renameSync(claudeMd, backupMd);
    }
  } else {
    fs.renameSync(claudeMd, backupMd);
  }

  try {
    const stat = fs.lstatSync(agentsDir);
    if (stat.isSymbolicLink()) {
      fs.unlinkSync(agentsDir);
    }
  } catch {
    // agents dir doesn't exist
  }

  removeHook(global ? os.homedir() : process.cwd(), global);
  const modeLabel = global ? 'global' : 'project';
  console.log(`\n  ${c.red('●')} ${c.purple('🐦 AgentCrow')} ${c.yellow('disabled')} ${c.dim(`(${modeLabel})`)} — CLAUDE.md backed up. Run ${c.cyan(`agentcrow on${global ? ' --global' : ''}`)} to re-enable.\n`);
}

export function cmdOn(global: boolean = false): void {
  const base = global ? path.join(os.homedir(), '.claude') : path.join(process.cwd(), '.claude');
  const claudeMd = path.join(base, 'CLAUDE.md');
  const backupMd = path.join(base, 'CLAUDE.md.agentcrow-backup');
  const agentsDir = path.join(base, 'agents');

  if (fs.existsSync(claudeMd)) {
    const content = fs.readFileSync(claudeMd, 'utf-8');
    if (content.includes('AgentCrow') || content.includes('agentcrow')) {
      console.log(`\n  ${c.green('●')} ${c.purple('🐦 AgentCrow')} already ${c.green('ON')}\n`);
      installHook(global ? os.homedir() : process.cwd(), global);
      return;
    }
  }

  if (fs.existsSync(backupMd)) {
    const backupContent = fs.readFileSync(backupMd, 'utf-8');

    if (fs.existsSync(claudeMd)) {
      const backupStart = backupContent.indexOf(AGENTCROW_START);
      const backupEnd = backupContent.indexOf(AGENTCROW_END);
      if (backupStart !== -1 && backupEnd !== -1 && backupEnd > backupStart) {
        const agentCrowSection = backupContent.slice(backupStart, backupEnd + AGENTCROW_END.length);
        const current = fs.readFileSync(claudeMd, 'utf-8');
        fs.writeFileSync(claudeMd, current.trimEnd() + '\n\n---\n\n' + agentCrowSection + '\n', 'utf-8');
      } else {
        fs.writeFileSync(claudeMd, backupContent, 'utf-8');
      }
    } else {
      fs.renameSync(backupMd, claudeMd);
    }

    if (fs.existsSync(backupMd)) fs.unlinkSync(backupMd);

    if (!fs.existsSync(agentsDir) && fs.existsSync(GLOBAL_MD)) {
      try {
        fs.symlinkSync(GLOBAL_MD, agentsDir, 'dir');
      } catch {
        // symlink failed, non-critical
      }
    }

    installHook(global ? os.homedir() : process.cwd(), global);
    console.log(`\n  ${c.green('●')} ${c.purple('🐦 AgentCrow')} ${c.green('re-enabled')} — restored from backup.\n`);
  } else {
    console.log(`\n  ${c.yellow('⚠')} No backup found. Run ${c.cyan(`agentcrow init${global ? ' --global' : ''}`)} first.\n`);
  }
}

export function cmdStatus(global: boolean = false): void {
  const hasAgr = fs.existsSync(GLOBAL_DIR);

  const scopes: Array<{ label: string; base: string }> = [];
  if (global) {
    scopes.push({ label: 'global', base: path.join(os.homedir(), '.claude') });
  } else {
    scopes.push({ label: 'project', base: path.join(process.cwd(), '.claude') });
    scopes.push({ label: 'global', base: path.join(os.homedir(), '.claude') });
  }

  console.log();
  for (const { label, base } of scopes) {
    const claudeMd = path.join(base, 'CLAUDE.md');
    const hasClaude = fs.existsSync(claudeMd);

    if (hasClaude && hasAgr) {
      const content = fs.readFileSync(claudeMd, 'utf-8');
      const isAgentCrow = content.includes('AgentCrow') || content.includes('agentcrow');

      if (isAgentCrow) {
        let builtinCount = 0;
        let externalCount = 0;
        const builtinDir = path.join(GLOBAL_DIR, 'builtin');
        if (fs.existsSync(builtinDir)) {
          builtinCount = fs.readdirSync(builtinDir).filter((f) => f.endsWith('.yaml')).length;
        }
        const mdDir = path.join(GLOBAL_DIR, 'md');
        if (fs.existsSync(mdDir)) {
          externalCount = Math.max(0, fs.readdirSync(mdDir).filter((f) => f.endsWith('.md')).length - builtinCount);
        }
        const totalCount = builtinCount + externalCount;
        console.log(`  ${c.green('●')} ${c.purple('🐦 AgentCrow')} ${c.green('ON')} ${c.dim(`(${label})`)}`);
        console.log(`    ${c.bold(String(builtinCount))} builtin + ${c.bold(String(externalCount))} external = ${c.bold(String(totalCount))} agents`);
        console.log(`    ${c.dim(`CLAUDE.md: ${claudeMd}`)}`);
        console.log(`    ${c.dim(`Agents:    ${GLOBAL_DIR}`)}`);
      } else {
        console.log(`  ${c.dim('●')} ${c.dim(`(${label})`)} .claude/CLAUDE.md exists but no AgentCrow section`);
      }
    } else if (hasAgr) {
      console.log(`  ${c.red('●')} ${c.dim(`(${label})`)} agents installed but CLAUDE.md missing. Run ${c.cyan(`agentcrow init${label === 'global' ? ' --global' : ''}`)}`);
    } else {
      console.log(`  ${c.dim('●')} ${c.dim(`(${label})`)} not installed — Run ${c.cyan('agentcrow init --global')}`);
    }
  }
  console.log();
}
