import * as fs from 'node:fs';
import * as path from 'node:path';
import type { CatalogEntry } from '../core/types.js';

/**
 * Generate INDEX.md — a lightweight catalog that Claude can scan
 * to find the right agent without opening all 144+ .md files.
 *
 * Format: one line per agent with role, name, description, and file link.
 * Grouped by division for easy scanning.
 */
export function generateAgentIndex(agents: CatalogEntry[], outputDir: string): void {
  // Group by division
  const grouped: Record<string, CatalogEntry[]> = {};
  for (const agent of agents) {
    const div = agent.source.type === 'builtin' ? 'builtin' : agent.division;
    if (!grouped[div]) grouped[div] = [];
    grouped[div].push(agent);
  }

  // Sort divisions: builtin first, then alphabetical
  const divisions = Object.keys(grouped).sort((a, b) => {
    if (a === 'builtin') return -1;
    if (b === 'builtin') return 1;
    return a.localeCompare(b);
  });

  const lines: string[] = [
    '# Agent Index',
    '',
    `> ${agents.length} agents across ${divisions.length} divisions. Find the right agent by role, then open its .md file for the full definition.`,
    '',
  ];

  for (const div of divisions) {
    const entries = grouped[div];
    lines.push(`## ${div} (${entries.length})`);
    lines.push('');
    lines.push('| Role | Name | Description |');
    lines.push('|------|------|-------------|');

    for (const entry of entries) {
      const safeRole = entry.role.replace(/[^a-z0-9_]/g, '_');
      const desc = (entry.description || '').replace(/\|/g, '∣').slice(0, 80);
      lines.push(`| [${entry.role}](${safeRole}.md) | ${entry.name} | ${desc} |`);
    }

    lines.push('');
  }

  lines.push('---');
  lines.push('*Generated by AgentCrow. Do not edit manually — run `agentcrow init` to regenerate.*');

  fs.writeFileSync(path.join(outputDir, 'INDEX.md'), lines.join('\n'), 'utf-8');
}
